class DetailRecipeItems {
  final String image, title, intro, stage;
  final int prep, cook, services;
  final List<String> ingredients, info;

  DetailRecipeItems({
    required this.image,
    required this.title,
    required this.intro,
    required this.stage,
    required this.prep,
    required this.cook,
    required this.services,
    required this.ingredients,
    required this.info,
  });
}

List<DetailRecipeItems> detailRecipeItems = [
  DetailRecipeItems(
    image: "assets/images/paneer.jpg",
    title: "Kadhai Paneer",
    intro:
        "Anyone can make a thick and luscious gravy with this easy kadhai paneer recipe. Ready to serve in just under an hour, this kadhai paneer recipe will become your go-to. If you have guests coming who love paneer dishes, then you can try this Kadhai Paneer recipe and impress them with your skills. This popular North Indian recipe is ideally enjoyed with naan, paratha or rice. The traditional Kadhai Paneer recipe is a perfect mix of spices, paneer and cream. If you are bored with the usual paneer recipes like shahi paneer, palak paneer, paneer bhurji; then this one is a must-try for you, especially if you are looking for something spicy and delicious! Here’s how you can make this Kadhai Paneer recipe in restaurant style at home by following a few simple steps given below.",
    stage: "Medium",
    prep: 15,
    cook: 30,
    services: 4,
    ingredients: [
      "250 gm paneer",
      "4 tomato",
      "1 medium chopped into cubes capsicum ( green pepper)",
      "1/2 cup fresh cream",
      "1/4 teaspoon powdered turmeric",
      "1 1/2 tablespoon garlic paste",
      "3 tablespoon ghee",
      "1 teaspoon coriander powder",
      "1 handful coriander leaves",
      "2 medium chopped onion",
      "5 medium green chilli",
      "1 teaspoon kasoori methi powder",
      "1 teaspoon garam masala powder",
      "2 teaspoon ginger paste",
      "1/2 cup water",
      "salt as required",
      "2 teaspoon red chilli powder",
    ],
    info: [
      "Prepare the masala for the gravy\nTo make this easy recipe, heat ghee in a pan and add chopped onions. Pan-fry the onions until aromatic and light golden brown. Grind tomatoes in a grinder to make a puree and pour in the pan. Cook till masala leaves the sides of the pan or ghee floats around the sides.",
      "Cook the masala with capsicum and the ground spices\nStir the mixture well and add ginger-garlic paste. Now, add in the spices-red chilli powder, garam masala, coriander powder, salt and turmeric powder. Add the cubed capsicum and the baby onions and some water to make a smooth gravy. Cook for about 2 minutes.",
      "Cook the paneer with this gravy and garnish with cream\nNow, add paneer and Kasuri methi into the pan and let it cook on a medium flame for another 4-5 minutes. Now, stir in the fresh cream gently. Garnish with some green chillies and coriander leaves and serve hot!",
    ],
  ),
  DetailRecipeItems(
    image: "assets/images/coffee.jpg",
    title: "Dark Chocolate Coffee",
    intro:
        "It’s a simple drink that combines creamy dark chocolate and freshly brewed coffee. Feel free to use any coffee brand or flavor you enjoy. Just keep in mind it needs to mix with dark chocolate. Beyond that, simply combine the 2 flavors for a slightly sweet beverage that keeps you warm and cozy.",
    stage: "Easy",
    prep: 10,
    cook: 15,
    services: 2,
    ingredients: [
      "2 Shot coffee",
      "2 tablespoon honey",
      "1 cup heavy cream",
      "1 cup dark chocolate",
      "1 teaspoon cocoa powder",
    ],
    info: [
      "Melt the dark chocolate\nTo make this classic coffee recipe, take a pan and add in dark chocolate cubes. once the chocolate cubes start melting, add in cocoa powder. Mix it together.",
      "Prepare the blend\nOnce the cocoa powder and melted chocolate is mixed nicely. Add in 2 coffee shots along with heavy cream. Simmer the blend for 3-4 minutes, till it smooth and thick.",
      "Serve hot\nPour the blend in cups of your choice and add in 1 tablespoon honey and mix it nicely. Serve hot with cookies.",
    ],
  ),
  DetailRecipeItems(
    image: "assets/images/chicken.jpg",
    title: "Butter Chicken Biryani",
    intro:
        "What better than the two most loved dishes of North Indians, Butter chicken and Biryani, collaborating and coming up as one fine irresistible meal that will satisfy your taste buds like never before! This Butter Chicken Biryani recipe does not need any introduction, the amazing aroma and the chicken cooked in a buttery and mouth-watering gravy allows it to stand out from rest of the other biryanis you'll ever have or have had. This biryani recipe is a perfect meal for any festive season and we assure you, it's going to become a family favourite once you serve it in your next family get together. Enjoy it with a raita of your choice!",
    stage: "Hard",
    prep: 40,
    cook: 60,
    services: 5,
    ingredients: [
      "1 kilograms chicken boneless",
      "2 onion",
      "1 tablespoon butter",
      "400 gm parboiled basmati rice",
      "2 cinnamon stick",
      "2 green cardamom",
      "1/2 cup vegetable oil",
      "1 cup tomato puree",
      "mint leaves as required",
      "2 tablespoon fresh cream",
      "1 teaspoon sugar",
      "2 bay leaf",
      "2 clove",
      "1 cup hung curd",
      "1 teaspoon ginger paste",
      "1 teaspoon garlic paste",
      "1 tablespoon cashew nut paste",
      "2 teaspoon red chilli powder",
      "salt as required",
      "2 tablespoon coriander powder",
      "1 teaspoon garam masala powder",
      "1/2 handful coriander leaves",
    ],
    info: [
      "Marinate the boneless chicken pieces in curd along with cashew paste, salt as per taste, garam masala powder, red chili powder, coriander powder and ginger-garlic paste. Let the chicken marinate for half an hour.",
      "In a thick-bottomed pan, heat butter over medium flame. Add the whole spices in it and let them saute for a few seconds. Then, add the marinated chicken pieces to the pan and fry over medium flame, make sure to stir in between so as to prevent them sticking to the bottom. Then, add tomato puree along with coriander leaves to the pan and mix well, switch the gas flame to low.",
      "Meanwhile, in a separate pan pour oil to fry the onions. When the oil is hot enough, shallow fry the thinly sliced onion and once fried well, add it to the pan. Save some of the fried onions for garnishing.",
      "Now, add fresh cream to the pan of chicken pieces along with a layer of parboiled rice and mint leaves. Make a final layer of the rest of the fried onions and add saffron milk on top. Cover the pan using a lid and seal it with a dough made of wheat flour. Cook the biryani on low flame till for 40-45 minutes. Once done, serve hot with raita.",
    ],
  ),
];

List<DetailRecipeItems> specialItems = [
  DetailRecipeItems(
    image: "assets/images/egg.jpg",
    title: "Century Egg",
    intro:
        "Century egg is a Chinese cuisine that has a greenish black colour with a delicious cheesy creamy flavour and strong aroma. It takes time to prepare this recipe as the eggs are pickled and preserved for a long time. This authentic Chinese recipe is fun trying. Made using duck egg, lime, dark vinegar and salt, providing this lip-smacking pickle with a refreshing taste, this easy-to-make recipe is sure to be loved by people of all age groups. So go ahead, introduce this amazing mouth-watering dish to your favourite people and relish the flavorful eggs together. You can also serve them on various occasions as a side dish to make many mouths water in one go.",
    stage: "Easy",
    prep: 20,
    cook: 10,
    services: 4,
    ingredients: [
      "4 duck eggs",
      "1/3 tablespoon salt",
      "4 tablespoon lime",
      "1 cup dark vinegar",
    ],
    info: [
      "To prepare a preserved eggs, preserve chicken or duck eggs in a mixture of salt, lime and dark vinegar and wrap it in rice husks for several weeks.",
      "Wash the preserved egg properly and shell them.",
      "Cut them into 4 parts and serve it in a ham or sandwhich of your choice.",
    ],
  ),
  DetailRecipeItems(
    image: "assets/images/rasgulla.jpg",
    title: "Rasagulla",
    intro:
        "If you are looking for a soft and spongy rasgulla recipe, then you are in the right place. Never made rasgulla before? No need to worry, like this super quick and easy rasgulla recipe with step by step photos will be your saviour. Festivals in India are incomplete with rasgulla, rasagola or rosogulla. This soft and spongy rasgulla recipe is one of the most well-known Indian sweet recipes that is prepared with curdled milk. While it may look complicated, making rasgulla is not difficult at all. This traditional Indian dessert recipe just requires homemade cheese, also known as chenna. Traditionally made in Orissa and Bengal, Rasgulla is mostly soft and spongy and is mildly sweet. If we compare it with the other Indian desserts like Malpua, Gulab Jamun, Jalebi or even Balushahi, Rasgulla is the juiciest dessert of them all and also the healthiest! This rasgulla recipe is so popular that in Odisha, it has a dedicated day called Rasagola Dibasa, which is otherwise known as the return of Lord Jagannath and celebrates the history and origin of this dish. If you are also a fan of this soft and spongy rasgulla, here is a simple and easy recipe that you can follow. This original rasgulla recipe gives you a step-by-step peek into how this dish is made. So, what are you waiting for? Try this amazing dessert and enjoy with your loved ones!",
    stage: "Hard",
    prep: 15,
    cook: 60,
    services: 4,
    ingredients: [
      "2 litre milk",
      "1 1/2 cup sugar",
      "3 cup water",
      "1 teaspoon rose water",
      "3 tablespoon lime juice",
      "3 cup water",
      "1 tablespoon all purpose flour",
      "2 teaspoon powdered green cardamom",
    ],
    info: [
      "Prepare the chhena\nMaking Rasgulla is a child's play if you know the right steps and almost everyone can make this delicious mithai. Take a heavy-bottomed pan and add two litres of full-cream milk to it. When it comes to a boil, reduce the flame and add the lemon juice. Your milk may take a while to curdle and you may require to add a little more lemon juice. Once the milk starts curdling, keep the flame low and allow boiling for 2-3 minutes so that the whey and chhena separates.",
      "Strain the chhena from whey\nSwitch off the gas. At this point, you can clearly see the green whey and the paneer or chhena which will separate from the water and stand out as small chunks.",
      "Strain the whey\nAllow the hot liquid to cool for 10-15 minutes. Now take a muslin cloth or a large strainer and strain away from the whey. Wash it in running water to remove the smell of lemon. You can store this whey and use it in soups and stews or curries. It is very nutritious. Many people also like to drink it by adding a little salt or sugar.",
      "Allow the water to separate\nTie it in the muslin cloth once the chenna cools a bit, squeeze away extra water and allow it to hang for some time. Do not refrigerate or it will make the chhena rubbery. This process may take 3-4 hours.",
      "Prepare sugar syrup\nHeat water in a pan. When it comes to a boil, add sugar and allow it to simmer on low flame. After 10 minutes, check the syrup by taking a drop of the syrup in a spoon. If it is of one string consistency, your syrup is ready. Add the juice of half a lemon. This will prevent the syrup from granulating later. Also, add gulab jal and cardamom powder. Switch off the gas.",
      "Knead the chhena\nTake the chhena from the muslin cloth and keep rubbing portions of it from your hand. At this point, you can add the maida. You have to rub it enough so that it becomes completely smooth and starts releasing a little oil. Once your chhena is smooth enough and much lighter in texture, make smooth round balls and keep aside.",
      "Boil the rasgullas\nMeanwhile heat the sugar syrup again, till it reaches a boiling point. Make sure you make small balls as they will swell up once they absorb the syrup. Add the rasgullas one by one in the syrup ensuring there is enough space in the pan. Boil for 5-7 minutes on low flame. Do not stir.",
      "Cook covered\nNow cover the pan and allow it to simmer on low flame for 5-7 minutes. When you remove the lid, you will be delighted to see that the rasgullas have swelled up and are looking beautiful! Switch off the flame and allow it to cool.",
      "Enjoy!\nThe rasgullas can be enjoyed warm or cold. You can also relish them topped with fruits or ice cream. Make sure you try this recipe, rate it and let us know how it turned out to be.",
    ],
  ),
  DetailRecipeItems(
    image: "assets/images/oats.jpg",
    title: "Masala Oats",
    intro:
        "A wholesome and yummy breakfast, brimming with the goodness of oats and flavours of chilli, ginger and garlic!",
    stage: "Easy",
    prep: 10,
    cook: 10,
    services: 2,
    ingredients: [
      "1 Cups Oats",
      "1 small Onion (Chopped)",
      "1 small Tomato (Chopped)",
      "2 tbsp Carrot (Chopped)",
      "2 Green Chillies",
      "2 tbsp Peas",
      "1/2 tsp Garam Masala",
      "to taste Red Chilli Powder",
      "1 tsp Turmeric Powder",
      "to taste Salt"
    ],
    info: [
      "To begin with the recipe, take 1 cup of oats and roast them until crispy. Once done, keep aside.",
      "Heat ghee in a pan, add cumin seeds and let them splutter. Then add ginger-garlic paste and saute for a minute.",
      "Then add chopped onion and fry until translucent. Once done, add all the veggies and saute for 5-6 minutes.",
      "Now add turmeric powder and salt. Mix well.",
      "Add garam masala, coriander powder, red chilli powder and mix again.",
      "Pour water as required and then add roasted oats.",
      "Cover for 5-6 minutes."
    ],
  ),
  DetailRecipeItems(
    image: "assets/images/tikka.jpg",
    title: "Chicken Tikka",
    intro:
        "If you have a party planned at home then should definitely try this easy-to-make chicken recipe, which is absolutely delicious and will be ready in no time! This appetizer recipe is a true delight for all the non-vegetarians as it's succulent and is cooked using broiling method, which makes the dish healthy and nutritious at the same time. Chicken Tikka is an apt dish for occasions like kitty party and game night, and will be ready in just 45-minutes.",
    stage: "Medium",
    prep: 15,
    cook: 30,
    services: 4,
    ingredients: [
      "500 gm chicken thighs",
      "250 gm chopped into cubes red bell pepper",
      "1 chopped into cubes onion",
      "2 tablespoon refined oil",
      "1/2 cup yoghurt (curd)",
      "1 teaspoon chili powder",
      "1 teaspoon coriander powder",
      "1/2 teaspoon cumin powder",
      "1/2 teaspoon kasoori methi powder",
      "1 teaspoon garlic paste",
      "2 tablespoon lemon juice",
      "1 teaspoon paprika",
      "1/4 teaspoon garam masala powder",
      "1/2 teaspoon caraway seeds",
      "1 teaspoon ginger paste",
    ],
    info: [
      "To prepare this delicious tikka recipe, prepare the marinade first by mixing together lemon juice, coriander powder, paprika, cumin powder, caraway seeds, aksoori methi powder, ginger-garlic paste, chilli powder and yoghurt in a large bowl. Next, preheat oven at 450 degree Fahrenheit. Next, wash chicken thighs well in running water and pat them dry. Cut them into bite-sized pieces in a large bowl.",
      "Add chopped chicken, bite-sized onion pieces and chopped bell peppers in the bowl of marinade. Using your hands, mix well and set aside for about 1-2 hours and let them marinate.",
      "After some time, thread the chicken on to the skewers, followed by onion and bell peppers. Brush oil on all of them.",
      "Broil these chicken pieces along with onion and bell peppers in oven on high speed for 15 minutes. Flip sides, brush the oil and broil for another 15 minutes or till the chicken meat is browned well.",
      "Once done, serve the chicken tikka on a bed of lettuce, sliced onions, tomatoes and lemon wedges.",
    ],
  ),
  DetailRecipeItems(
    image: "assets/images/sandwich.jpg",
    title: "Sandwich",
    intro:
        "Remember the popular Hollywood flick that revolved around the pyramids and The Return of the Mummys from the grave. This Halloween recreate the spooky chills in your kitchen and please the palate of your guests with these simple open sandwiches that taste like Margherita pizza but are super easy to make. All you need is some spicy tomato sauce, cheese slices, oregano chili flakes, black olive slices and butter. So, try these Spooky Bandaged sandwiches. They are not just scary but also delicious.",
    stage: "Easy",
    prep: 10,
    cook: 10,
    services: 2,
    ingredients: [
      "5 bread slices",
      "3 tablespoon tomato chili sauce",
      "black olives as required",
      "chilli flakes as required",
      "2 tablespoon butter",
      "6 pieces cheese slices",
      "oregano as required",
    ],
    info: [
      "Toast the bread\nTake bread slices, toast them by spreadin some butter.",
      "Cut the cheese slice\nThen spread some tomato chilli ketchup and cut thin strips of cheese slices giving a bandage effect.",
      "Serve hot\nLayer the open sandwich and make eyes with olive slices. Sprinkle some oregano and chilli flakes and bake for 2-3 minutes to melt the cheese. Serve hot."
    ],
  ),
];
