// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_uUZv0g4jf68KtiTFP5_tdqYbcboQmQk',
    appId: '1:584033225096:web:6dfadf5bee0597f27d523d',
    messagingSenderId: '584033225096',
    projectId: 'herbs-and-spices-966f5',
    authDomain: 'herbs-and-spices-966f5.firebaseapp.com',
    storageBucket: 'herbs-and-spices-966f5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUoymvNSIG5ZFYTR0YqnMqoIShxMfq0ho',
    appId: '1:584033225096:android:a84ce5d153ad8f037d523d',
    messagingSenderId: '584033225096',
    projectId: 'herbs-and-spices-966f5',
    storageBucket: 'herbs-and-spices-966f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw3KS_fy3gtKw4R46rpYYxoblbERVpBag',
    appId: '1:584033225096:ios:e74b6115b2a8e7ba7d523d',
    messagingSenderId: '584033225096',
    projectId: 'herbs-and-spices-966f5',
    storageBucket: 'herbs-and-spices-966f5.appspot.com',
    iosClientId: '584033225096-lfbi2j67b51nnk1nj9uj9s87dmvrtlkl.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodRecipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw3KS_fy3gtKw4R46rpYYxoblbERVpBag',
    appId: '1:584033225096:ios:e74b6115b2a8e7ba7d523d',
    messagingSenderId: '584033225096',
    projectId: 'herbs-and-spices-966f5',
    storageBucket: 'herbs-and-spices-966f5.appspot.com',
    iosClientId: '584033225096-lfbi2j67b51nnk1nj9uj9s87dmvrtlkl.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodRecipe',
  );
}
